### ISSUE TITLE
Reverse engineer?

### ISSUE THREAD

**Issue by SnesLover22** [ekoerp1/BlockerExtensionRemover-Patched-Verson-106-Use-3kh0s-respitory-for-updated-version-#1]
can you reverse engineer it to download extensions?

**Comment by ekoerp1** [comment]
Yes, but it would have to not be blocked by admins and/or installed through dev mode.

**Comment by SnesLover22** [comment]
use Ingot v1 to turn on dev mode?

**Comment by ekoerp1** [comment]
No, you would use the extension launcher on the main page

**Comment by SnesLover22** [comment]
could you post a tutorial?
